baseURL = 'https://example.org/'
languageCode = 'zh-cn'
title = '识字汉教'

[params]
  editURL = "https://nightttg.github.io/shizihanjiao.io"

  author = "hightttg"

  description = "用于辅助中小学教师使用甲骨文教书的网站"

  showVisitedLinks = false

  disableSearch = false

  disableAssetsBusting = false

  disableInlineCopyToClipBoard = false

  disableShortcutsTitle = false

  disableLandingPageButton = false

  disableLanguageSwitchingButton = false

  disableBreadcrumb = true

  disableMermaid = false

  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"

  disableNextPrev = true
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"

  themeVariant = "learn"

  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css = ["css/foo.css", "css/bar.css"]
  # Change the title separator. Default to "::".
  titleSeparator = "-"
  
[outputs]
  home = ['html', 'rss', 'search', 'searchpage']

[module]
  [module.hugoVersion]
    min = "0.124.1"

[mediaTypes]
  [mediaTypes."text/javascript"]
    suffixes = ["js"]

[outputFormats]
  [outputFormats.print]
    name= "print"
    baseName = "index.print"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

  [outputFormats.search]
    name= "search"
    baseName = "index.search"
    isPlainText = true
    mediaType = 'text/javascript'
    permalinkable = false
    noUgly = true

  [outputFormats.searchpage]
    name= "searchpage"
    baseName = "search"
    isHTML = true
    mediaType = 'text/html'
    permalinkable = false
    noUgly = true

[params.relearn.dependencies]
  [params.relearn.dependencies.mathjax]
    name = "MathJax"
    location = "footer"
  [params.relearn.dependencies.mermaid]
    name = "Mermaid"
    location = "footer"
  [params.relearn.dependencies.openapi]
    name = "OpenApi"
    location = "footer"

defaultContentLanguage = 'zh'
defaultContentLanguageInSubdir = true
[Languages]
[Languages.zh]
contentDir = 'content/ch'
title = "甲骨文辅助教学网站"
weight = 1
languageName = "简体中文"

[[Languages.zh.menu.shortcuts]]
name = "<i class='fab fa-github'></i> Repo Github"
identifier = "ds"
url = "https://github.com/KIOSHIROI/shizihanjiao.io"
weight = 10

[Languages.en]
contentDir = 'content/en'
title = "Documentation for Hugo Learn Theme"
weight = 2
languageName = "English"

[[Languages.en.menu.shortcuts]] 
name = "<i class='fab fa-github'></i> Github repo"
identifier = "ds"
url = "https://github.com/KIOSHIROI/shizihanjiao.io"
weight = 10

#[[menu.shortcuts]]
#name = "<i class='fas fa-camera'></i> Showcases"
#url = "/showcase"
#weight = 11

#[[menu.shortcuts]]
#name = "<i class='fas fa-bookmark'></i> Hugo Documentation"
#identifier = "hugodoc"
#url = "https://gohugo.io/"
#weight = 20

#[[menu.shortcuts]]
#name = "<i class='fas fa-bullhorn'></i> Credits"
#url = "/credits"
#weight = 30


